# Generated by Django 2.2.2 on 2019-06-21 00:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('92bf46ed-42bb-4b6d-b873-a763cc338c2b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='id',
            field=models.UUIDField(default=uuid.UUID('092da077-9591-4ccd-af4f-193f50ca72d6'), editable=False, primary_key=True, serialize=False),
        ),
    ]
